# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
warnings_are_errors: false

r_packages:
    - covr

r_github_packages:
    - skeydan/reticulate@40aebd90f40e21762965770b00edf819730d9225
cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "tf-stable"
      env: TENSORFLOW_VERSION="1.14"
    - name: "2.0.0b1"
      env:
        - TENSORFLOW_VERSION="2.0.0b1"
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="tf-nightly"
   allow_failures:
    - name: "2.0.0b1"
      env:
        - TENSORFLOW_VERSION="2.0.0b1"
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="tf-nightly"

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = if (substr(Sys.getenv("TENSORFLOW_VERSION"), 1, 4) %in% c("1.14")) "tensorflow-probability" else "tfp-nightly")'
  - R -e 'tensorflow::tf_config()'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'testthat::test_dir("tests/testthat/")'

notifications:
  email:
    recipients:
      - sigrid@rstudio.com
    on_success: never
    on_failure: always
