# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
warnings_are_errors: false

r_packages:
    - covr

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "tf-stable"
      env: TENSORFLOW_VERSION="1.14"
    - name: "tf-nightly-2.0-preview"
      env:
        - TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/2c/29/793aee1dba76c38d8d34b4c5627f2003f4a2d8b9772b1a6266835ab0f04a/tf_nightly_2.0_preview-2.0.0.dev20190719-cp27-cp27mu-manylinux1_x86_64.whl"
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
  allow_failures:
    - name: "tf-nightly-2.0-preview"
      env:
        - TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/2c/29/793aee1dba76c38d8d34b4c5627f2003f4a2d8b9772b1a6266835ab0f04a/tf_nightly_2.0_preview-2.0.0.dev20190719-cp27-cp27mu-manylinux1_x86_64.whl"
    - name: "tf-nightly"
      env:
        - TENSORFLOW_VERSION="nightly"

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = if (substr(Sys.getenv("TENSORFLOW_VERSION"), 1, 4) %in% c("1.14")) "tensorflow-probability" else "tfp-nightly")'
  - R -e 'tensorflow::tf_config()'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'testthat::test_dir("tests/testthat/")'

notifications:
  email:
    recipients:
      - sigrid@rstudio.com
    on_success: never
    on_failure: always
